services:
  db:
    image: 
      postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=better-uptime

  redis-client:
    image:
      redis
    ports:
      - 6379:6379
    